### Most Popular Movie Simple Recommendation

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tests as t

%matplotlib inline

# Read in the datasets
movies = pd.read_csv('movies_clean.csv')
reviews = pd.read_csv('reviews_clean.csv')
del movies['Unnamed: 0']
del reviews['Unnamed: 0']

In [10]:
reviews.head()
# shape(863866, 5)

   user_id  movie_id  rating   timestamp                 date
0        1    114508       8  1381006850  2013-10-05 21:00:50
1        2    208092       5  1586466072  2020-04-09 21:01:12
2        2    358273       9  1579057827  2020-01-15 03:10:27
3        2  10039344       5  1578603053  2020-01-09 20:50:53
4        2   6751668       9  1578955697  2020-01-13 22:48:17

In [4]:
reviews[(reviews['user_id'] == 2)]['rating'].count()

10

In [5]:
reviews[(reviews['movie_id'] == 10039344 )]['rating'].mean()

5.1226993865030677

In [11]:
#full_movies = pd.merge(reviews,movies,on='movie_id')

In [3]:
#full_movies.head()

In [5]:
#last_rate = pd.DataFrame(reviews.groupby('movie_id').max()['date'])

In [6]:
reviews[reviews['user_id'] == 3 ]

    user_id  movie_id  rating   timestamp                 date
11        3    790636       8  1391207279  2014-01-31 22:27:59
12        3   1800241       7  1388955438  2014-01-05 20:57:18
13        3   2278871       8  1383419733  2013-11-02 19:15:33
14        3   2395417       8  1388170007  2013-12-27 18:46:47
15        3   3344922       8  1422652427  2015-01-30 21:13:47

#### To Find The Most Popular Movies

"most popular" based on the following criteria:

* A movie with the highest average rating is considered best
* With ties, movies that have more ratings are better
* A movie must have a minimum of 5 ratings to be considered among the best movies
* If movies are tied in their average rating and number of ratings, the ranking is determined by the movie that is the most recent rating

With these criteria, the goal is to take a **user_id** and provide back the **n_top** recommendations.

In [7]:
def ranked_df (movies, reviews):
    '''
        INPUT
        movies - the movies dataframe
        reviews - the reviews dataframe
        
        OUTPUT
        ranked_movies - a dataframe with movies that are sorted by highest avg rating, more reviews, 
                        then time, and must have more than 4 ratings
    '''
    
    
    #avg_rate = reviews[(reviews['movie_id'] == x)]['rating'].mean()
    movies_rate = reviews.groupby('movie_id')['rating']
    avg_rate = movies_rate.mean()
    count_rate = movies_rate.count()
    last_rate = pd.DataFrame(reviews.groupby('movie_id').max()['date'])
    last_rate.columns = ['last_rate']
    
    # Add Dates
    rating_count_df = pd.DataFrame({'avg_rating': avg_rate, 'num_ratings': count_rate})
    rating_count_df = rating_count_df.join(last_rate)
    
    # merge the new df with the movies dataset
    movies_new = movies.set_index('movie_id').join(rating_count_df)
    # sort by top avg rating and number of ratings
    ranked_movies = movies_new.sort_values(['avg_rating','num_ratings','last_rate'], ascending=False)
    
    ranked_movies = ranked_movies[ranked_movies['num_ratings'] > 4]
    ranked_movies.head()
    return ranked_movies

In [61]:
x = ranked_df(movies, reviews)
x

,movie,genre,Date,1800's,1900's,2000's,Animation,Music,Reality-TV,Documentary,...,Mystery,Film-Noir,History,Comedy,Horror,Musical,Biography,avg_rating,num_ratings,last_rate
movie_id,,,,,,,,,,,,,,,,,,,,,
4921860,MSG 2 the Messenger (2015),Comedy|Drama|Fantasy|Horror,2015,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,10.000000,48,2016-08-14 17:16:50
5262972,Avengers: Age of Ultron Parody (2015),Short|Comedy,2015,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,10.000000,28,2016-01-08 00:44:43
6662050,Five Minutes (2017),Short|Comedy,2017,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,10.000000,22,2019-04-20 22:29:19
2737018,Selam (2013),Drama|Romance,2013,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,10.000000,10,2015-05-10 22:56:01
5804314,Let There Be Light (2017),Drama,2017,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,10.000000,7,2019-12-25 16:27:47
2560840,"Quiet Riot: Well Now You're Here, There's No W...",Documentary|Music,2014,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,10.000000,6,2016-01-23 00:30:44
2219210,Crawl Bitch Crawl (2012),Horror|Sci-Fi|Thriller,2012,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,10.000000,6,2013-07-22 23:30:52
9882084,Chasing Happiness (2019),Documentary,2019,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,10.000000,5,2019-06-29 03:37:46
4448444,Make Like a Dog (2015),Short|Comedy|Drama,2015,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,10.000000,5,2017-09-09 13:51:48
5131914,Pandorica (2016),Sci-Fi,2016,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,10.000000,5,2016-04-04 05:52:22
2059318,Third Contact (2011),Drama|Mystery|Sci-Fi|Thriller,2011,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,10.000000,5,2014-02-13 15:48:31
1431149,Romeo Juliet (2009),Drama,2009,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,10.000000,5,2013-07-26 17:19:01
5512872,Be Somebody (2016),Comedy|Drama|Romance,2016,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,9.985836,353,2018-05-17 00:29:18
4148400,Birlesen Gonuller (2014),Drama|History,2014,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,9.882353,17,2015-10-22 23:34:37
9536832,Kitbull (2019),Animation|Short|Drama|Family,2019,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,9.857143,7,2020-02-10 03:06:26
6798422,Agnelli (2017),Documentary,2017,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,9.800000,5,2018-05-15 22:39:34
111341,Sátántangó (1994),Drama,1994,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,9.800000,5,2018-03-09 08:09:54
1629443,Foster (2011),Comedy|Drama|Family,2011,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,9.800000,5,2014-03-15 23:37:57
2592910,CM101MMXI Fundamentals (2013),Documentary|Comedy,2013,0,0,1,0,0,0,1,...,0,0,0,1,0,0,0,9.666667,9,2013-09-20 13:43:47
2396421,Crystal Lake Memories: The Complete History of...,Documentary|Horror,2013,0,0,1,0,0,0,1,...,0,0,0,0,1,0,0,9.666667,6,2017-01-04 04:58:14
5732482,Hans Zimmer Live on Tour (2017),Documentary|Music,2017,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,9.600000,5,2019-09-01 19:58:06
6054758,Kirik Party (2016),Comedy|Drama,2016,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,9.600000,5,2017-01-05 06:52:16
5134588,Chasing Asylum (2016),Documentary,2016,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,9.600000,5,2016-07-18 12:01:43
363473,Beyond the Sea (2004),Biography|Drama|Music|Musical,2004,0,0,1,0,1,0,0,...,0,0,0,0,0,1,1,9.600000,5,2015-04-16 22:18:26
2265179,Blood Brother (2013),Documentary,2013,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,9.571429,7,2015-06-14 18:04:04
5323386,Poshter Girl (2016),Comedy,2016,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,9.555556,9,2016-04-09 17:15:36
8902990,The Sky Is Pink (2019),Drama|Family|Romance,2019,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,9.476190,21,2020-04-03 18:59:42
2357788,Bridegroom (2013),Documentary,2013,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,9.428571,14,2016-01-05 18:56:04
1826550,Mad As Hell (2014),Documentary|Biography|Comedy|Drama|History,2014,0,0,1,0,0,0,1,...,0,0,1,1,0,0,1,9.428571,7,2015-04-05 06:34:24
73440,Nashville (1975),Comedy|Drama|Music,1975,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,9.428571,7,2014-10-07 00:14:56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006801,Night of the Living Dead: Resurrection (2012),Horror,2012,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,2.666667,6,2013-12-27 16:07:36
3283792,Erkek tarafi testosteron (2013),Comedy|Drama,2013,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,2.600000,5,2013-12-09 15:18:25
5988370,Reis (2016),Biography|Drama,2016,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,2.500000,36,2018-12-05 21:14:51
5669936,The Recall (2017),Action|Sci-Fi|Thriller,2017,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,2.500000,6,2018-09-06 05:16:37
2325518,Beneath (2013),Horror|Sci-Fi|Thriller,2013,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,2.444444,9,2016-04-03 09:19:54
1540767,Apartment 1303 3D (2012),Horror,2012,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,2.434783,23,2016-09-19 17:37:17
3551400,Unnatural (2015),Action|Horror|Sci-Fi|Thriller,2015,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,2.400000,5,2017-11-02 00:09:08
2357489,Zanjeer (2013),Action|Thriller,2013,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,2.400000,5,2013-10-20 14:13:10
185183,Battlefield Earth (2000),Action|Adventure|Sci-Fi,2000,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,2.352941,17,2019-08-04 18:13:18
829176,Gallowwalkers (2012),Action|Horror|Thriller|Western,2012,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,2.269231,26,2018-02-07 04:59:11
3104304,Ice Soldiers (2013),Action|Sci-Fi,2013,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,2.200000,5,2017-03-24 23:43:04
2622826,Avalanche Sharks (2013),Action|Adventure|Comedy|Fantasy|Horror|Sci-Fi|...,2013,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,2.200000,5,2016-10-28 20:06:51
3561236,Containment (2015),Horror|Sci-Fi|Thriller,2015,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,2.200000,5,2016-06-17 20:43:01
3036740,Humshakals (2014),Comedy,2014,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,2.200000,5,2015-05-28 03:47:41
7086706,Deep Blue Sea 2 (2018),Action|Horror|Sci-Fi|Thriller,2018,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,2.166667,6,2018-12-05 01:29:32
1098327,Dragonball Evolution (2009),Action|Adventure|Fantasy|Sci-Fi|Thriller,2009,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,2.157895,19,2017-04-16 09:32:55
2147365,Keith Lemon: The Film (2012),Comedy,2012,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,2.142857,21,2015-02-01 00:52:05
93300,Jaws: The Revenge (1987),Adventure|Horror|Thriller,1987,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,2.142857,7,2020-04-26 23:16:11
105585,Thunderheart (1992),Crime|Mystery|Thriller,1992,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,2.133333,15,2017-05-22 04:43:49
2573750,Gulaab Gang (2014),Action|Drama,2014,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,2.000000,6,2015-01-11 07:04:42
4743562,The Last Heist (2016),Action|Horror|Thriller,2016,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,2.000000,5,2018-10-07 05:26:21
1213644,Disaster Movie (2008),Comedy,2008,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1.888889,18,2020-03-19 06:43:58
60666,Manos: The Hands of Fate (1966),Horror,1966,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1.857143,7,2018-05-06 19:18:10
3588588,Backtrace (2018),Crime|Drama,2018,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1.833333,6,2019-09-26 21:29:05
4475992,Belly of the Bulldog (2015),Action|Horror|Mystery|Sci-Fi|Thriller|War,2015,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,1.800000,5,2019-03-15 13:58:24
10367276,The Rat (2019),Short|Drama,2019,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1.736842,95,2020-03-23 19:20:07
3108604,American Poltergeist (2015),Horror|Thriller,2015,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1.666667,6,2018-10-14 17:47:29
3187378,The Asian Connection (2016),Action|Crime|Drama|Thriller,2016,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1.666667,6,2017-07-11 06:13:16
4458206,Kod Adi K.O.Z. (2015),Crime|Mystery,2015,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,1.000000,30,2018-01-20 04:44:12
7923374,Badang (2018),Comedy|Fantasy,2018,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1.000000,7,2018-02-24 03:21:51

In [49]:
def popular_recommendations(user_id, n_top, ranked_movies):
    '''
    INPUT:
    user_id - the user_id of the individual you are making recommendations for
    n_top - an integer of the number recommendations you want back
    OUTPUT:
    top_movies - a list of the n_top recommended movies by movie title in order best to worst
    '''
    #ranked_df.iloc[n_top]
    top_movies = list(ranked_movies['movie'][:n_top])
    
    return top_movies # a list of the n_top movies as recommended

In [44]:
ranked_movies = ranked_df(movies, reviews) # only run this once - it is not fast

In [52]:
# Top 20 movies recommended for id 1
recs_20_for_1 = popular_recommendations(1, 20, ranked_movies)
recs_20_for_1

['MSG 2 the Messenger (2015)',
 'Avengers: Age of Ultron Parody (2015)',
 'Five Minutes (2017)',
 'Selam (2013)',
 'Let There Be Light (2017)',
 "Quiet Riot: Well Now You're Here, There's No Way Back (2014)",
 'Crawl Bitch Crawl (2012)',
 'Chasing Happiness (2019)',
 'Make Like a Dog (2015)',
 'Pandorica (2016)',
 'Third Contact (2011)',
 'Romeo Juliet (2009)',
 'Be Somebody (2016)',
 'Birlesen Gonuller (2014)',
 'Kitbull (2019)',
 'Agnelli (2017)',
 'Sátántangó (1994)',
 'Foster (2011)',
 'CM101MMXI Fundamentals (2013)',
 'Crystal Lake Memories: The Complete History of Friday the 13th (2013)']

### Adding Filters

Add arguments that will act as filters for the movie **year** and **genre**.  
example:
```
popular_recs_filtered('1', 20, ranked_movies, years=['2015', '2016', '2017', '2018'], genres=['History'])

```

In [91]:
def popular_recs_filtered(user_id, n_top, ranked_movies, years=None, genres=None):
    '''
    INPUT:
    user_id - the user_id of the individual you are making recommendations for
    n_top - an integer of the number recommendations you want back
    OUTPUT:
    top_movies - a list of the n_top recommended movies by movie title in order best to worst
    '''

    #ranked_df.iloc[n_top]
    #ranked_movies = ranked_movies[ranked_movies['Date'] == years]
    # Filter movies based on year and genre
    if years is not None:
        ranked_movies = ranked_movies[ranked_movies['Date'].isin(years)]

    if genres is not None:
        num_genre_match = ranked_movies[genres].sum(axis=1)
        ranked_movies = ranked_movies.loc[num_genre_match > 0, :]
            
            
    # create top movies list 
    top_movies = list(ranked_movies['movie'][:n_top])


    return top_movies

In [92]:
popular_recs_filtered('1', 10, ranked_movies, years=['2015', '2016', '2017', '2018'], genres=['History'])

["Hillary's America: The Secret History of the Democratic Party (2016)",
 'I Believe in Miracles (2015)',
 'O.J.: Made in America (2016)',
 'Ayla: The Daughter of War (2017)',
 'Hacksaw Ridge (2016)',
 'They Shall Not Grow Old (2018)',
 'Namhansanseong (2017)',
 'The Farthest (2017)',
 'Kono sekai no katasumi ni (2016)',
 'Sado (2015)']